// dummyData.js
export const dataReportKendaraan = [
	{
		id: 1,
		date: '14 Apr 2021',
		employeeName: 'FULL NAME 1',
		department: 'Bagian MIS',
		destination: 'Meeting AGP',
		time: 'Siang 13:00 - 17:00',
		supervisor: 'FULL NAME 1',
		vehicleInfo: 'Toyota Avanza B 2100 UOL - Manual',
	},
	{
		id: 2,
		date: '14 Apr 2021',
		employeeName: 'FULL NAME 2',
		department: 'Bagian MIS',
		destination: 'Meeting AGP',
		time: 'Siang 13:00 - 17:00',
		supervisor: 'FULL NAME 2',
		vehicleInfo: 'Toyota Avanza B 2100 UOL - Manual',
	},
	{
		id: 3,
		date: '14 Apr 2021',
		employeeName: 'FULL NAME 3',
		department: 'Bagian MIS',
		destination: 'Meeting AGP',
		time: 'Siang 13:00 - 17:00',
		supervisor: 'FULL NAME 3',
		vehicleInfo: 'Toyota Avanza B 2100 UOL - Automatic',
	},
	{
		id: 4,
		date: '14 Apr 2021',
		employeeName: 'FULL NAME 4',
		department: 'Bagian MIS',
		destination: 'Meeting AGP',
		time: 'Siang 13:00 - 17:00',
		supervisor: 'FULL NAME 4',
		vehicleInfo: 'Toyota Avanza B 2100 UOL - Manual',
	},
	{
		id: 5,
		date: '14 Apr 2021',
		employeeName: 'FULL NAME 5',
		department: 'Bagian MIS',
		destination: 'Meeting AGP',
		time: 'Siang 13:00 - 17:00',
		supervisor: 'FULL NAME 5',
		vehicleInfo: 'Toyota Avanza B 2100 UOL - Automatic',
	},
	{
		id: 6,
		date: '14 Apr 2021',
		employeeName: 'FULL NAME 6',
		department: 'Bagian MIS',
		destination: 'Meeting AGP',
		time: 'Siang 13:00 - 17:00',
		supervisor: 'FULL NAME 6',
		vehicleInfo: 'Toyota Avanza B 2100 UOL - Dual Transmission',
	},
];
