// dummyData.js
export const dataKlaimBensinParkir = [
	{
		id: 1,
		employeeName: 'Employee 1',
		department: 'Department 1',
		date: '14 Apr 2021',
		destination: 'Destination 1',
		totalamount: 'Rp. 100.000',
	},
	{
		id: 2,
		employeeName: 'Employee 2',
		department: 'Department 2',
		date: '15 Apr 2021',
		destination: 'Destination 2',
		totalamount: 'Rp. 200.000',
	},
	{
		id: 3,
		employeeName: 'Employee 3',
		department: 'Department 3',
		date: '16 Apr 2021',
		destination: 'Destination 3',
		totalamount: 'Rp. 300.000',
	},
	{
		id: 4,
		employeeName: 'Employee 4',
		department: 'Department 4',
		date: '17 Apr 2021',
		destination: 'Destination 4',
		totalamount: 'Rp. 400.000',
	},
	{
		id: 5,
		employeeName: 'Employee 5',
		department: 'Department 5',
		date: '18 Apr 2021',
		destination: 'Destination 5',
		totalamount: 'Rp. 500.000',
	},
	{
		id: 6,
		employeeName: 'Employee 6',
		department: 'Department 6',
		date: '19 Apr 2021',
		destination: 'Destination 6',
		totalamount: 'Rp. 600.000',
	},
];
