import Footer from '@/components/Footer/Footer';
import NavbarMenu from '@/components/Navbar/Navbar';
import SidebarMenu from '@/components/Sidebar/Sidebar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ClientLayout from '@/components/ClientLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'BIG Forum 3.0',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} h-full`}>
				
			<ClientLayout>{children}</ClientLayout>
			</body>
		</html>
	);
}
